site_name: Портфолио IR6
site_description: Отчеты по лабораторным работам курса программирования на Python
site_author: IR6
site_url: https://IR630.github.io
docs_dir: docs

theme:
  name: material
  logo: assets/begemot.png
  favicon: assets/begemot.png
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Включить темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Включить светлую тему
  font:
    text: Outfit
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/custom.css

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Информация о курсе: course.md
  - Семестр 1:
      - Лабораторные работы 1-10: sem1.md
  - Семестр 2 (Лабораторные работы):
      - Лабораторная №1: LR-1.md
      - Лабораторная №2: LR-2.md
      - Лабораторная №4: LR-4.md
      - Лабораторная №5: LR-5.md
      - Лабораторная №6: LR-6.md
      - Лабораторная №7: LR-7.md
      - Лабораторная №8: LR-8.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
