site_name: Портфолио Лабораторных Работ IR6
site_description: Отчеты по лабораторным работам курса программирования на Python
site_author: IR6
site_url: https://IR630.github.io
docs_dir: docs

theme:
  name: material
  logo: assets/begemot.png
  favicon: assets/begemot.png
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Перейти в темный режим
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Перейти в светлый режим

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Информация о курсе: course.md
  - Лабораторные работы:
      - Лабораторная №1: LR-1.md
      - Лабораторная №2: LR-2.md
      - Лабораторная №4: LR-4.md
      - Лабораторная №5: LR-5.md
